#!/bin/bash

MOD_FILES=($(git diff --cached --name-only -- '*.go' ':(exclude)vendor/*'))
# TODOs:
# - (?) remove `--cached` flag?
# - It would be nice if the output of `git add --patch` could be
# launched by this script.

# If any element is find...
if (( ${#MOD_FILES[@]} > 0 )); then # [ "$a" -gt "$b" ];

    while true; do
        echo -e "The following files will be targeted for import fixes:"
        #  ${MOD_FILES[*]} will prompt all the files in the same line.
        for i in "${MOD_FILES[@]}"; do
            echo -e "\t$i"
        done

        read -p "Do you want to proceed? [y,n] " answer </dev/tty
        case $answer in
        [Yy]*) break ;;
        [Nn]*) exit 1 ;;
        *) echo "Please answer yes or no." ;;
        esac
    done

    for file in ${MOD_FILES[@]}; do
        echo "Fixing imports for ${file}" &&
            fiximports ${file} &&
            goimports -w -local=$AP_GITHUB ${file}
        git add ${file} # Doing this we trust in the fixes
        # and we are adding them every time, this is risky
        # because we will add any modified content unintentionally
    done

fi
