#!/bin/bash

# [INFO]
# pre-push hooks for git.
# Hook that runs all files specified, containing hooks with useful checks

HOOKS="pre-push-annotations" # Add here more files containing hooks...

for hook in $HOOKS; do
	path_to_hook="$HOME/.config/git/hooks/$hook"
    if [ -f $path_to_hook ]; then  # CHECK if hook exists.
        $path_to_hook  # RUN hook.
        if [ $? != 0 ]; then
            exit 1
        fi
    else
        echo "Error: file $path_to_hook not found."
        exit 1
    fi
done
