# Setting your PATH so that '/opt/homebrew/bin' occurs before '/usr/bin'
# Environment variables should be set in ~/.zprofile

eval $(/opt/homebrew/bin/brew shellenv)
export PATH=$PATH:"$HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin"

# https://go.dev/doc/gopath_code#GOPATH
export PATH=$PATH:$(go env GOPATH)/bin # Allows using tools after installing them via 'go install'
# export GOPATH=$(go env GOPATH) # Useful for scripts but not necessary
