#!/usr/bin/env zsh

# TODO checklist:
# [] Handle routing properly. I mean, variables like ZSH_CUSTOM_CONFIG_ALIASES start to be annoying.
#    I need to do a proper routes system that eventually can be tested when the terminal starts,
#    checking if a directory/file exists and raising an error/warning otherwise.
# [] zmodload zsh/zprof # This will enable the built in profiling. Recently used to analyse loading times.
# [] Make new iterm tabs run without plugins and shit :)

declare -A logs=() # -A: Associative (array)
# # timelogger can be used to start/end time logs. mainly used to display time intervals when running heavy processes.
# #
# # eg:
# #   timelogger heavyprocess start
# #   timelogger heavyprocess end

alias gdate="/opt/homebrew/bin/gdate"
timelogger() {
  local name=$1
  local action=$2
  if [ "$action" = "start" ]; then
    log_start=$(($(gdate +%s%N)/1000000))
    logs+=( [$name]=$log_start )
  fi
  if [ "$action" = "end" ]; then
    log_end=$(($(gdate +%s%N)/1000000))
    log_start=$logs[$name]
    log_runtime=$((log_end - log_start)); echo "Runtime of $name was $log_runtime ms."
    unset "logs[${(b)name}]"
  fi
}
timelogger zsh start

# alert_unused_logs alerts if any log remains unused.
alert_unused_logs(){
    for log value in ${(kv)logs}; do
      if [[ -n $logs[$value] ]]; then echo unused $key log value; fi
    done
}

# BUGFIX: Provisional fix for zsh errors
ZSH_DISABLE_COMPFIX="true" # fixes error prompting "Insecure completion-dependent directories..."

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$HOME/.oh-my-zsh/custom"


ZSH_THEME="spaceship"; SPACESHIP_BATTERY_SHOW='never'
# https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# https://github.com/denysdovhan/spaceship-zsh-theme
# https://github.com/mbadolato/iTerm2-Color-Schemes#installation-instructions

# IMPORTANT: oh-my-zsh must be installed for making next section work.
# What add-ons do you want to use? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    fzf                     # https://github.com/junegunn/fzf#using-homebrew-or-linuxbrew
    zsh-autosuggestions     # https://github.com/zsh-users/zsh-autosuggestions#oh-my-zsh
    zsh-syntax-highlighting # https://github.com/zsh-users/zsh-syntax-highlighting

    git
    git-extras
    gnu-utils

    golang
    docker
    docker-compose
    kubectl
)
source "$ZSH/oh-my-zsh.sh" # LOAD oh-my-zsh. This will load all the plugins.

# Path to your custom configuration.
export ZSH_CUSTOM_CONFIG_FILES="$HOME/.config/zshrc"
source "$ZSH_CUSTOM_CONFIG_FILES/config/config"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
# To reload .zshrc: 'source .zshrc' or just type 'zsh'

export ZSH_CUSTOM_CONFIG_ALIASES="$ZSH_CUSTOM_CONFIG_FILES/aliases"
alias zshrc="code $ZSH_CUSTOM_CONFIG_FILES"
alias .config="code ~/.config/config.code-workspace ~/.gitconfig"
source "$ZSH_CUSTOM_CONFIG_ALIASES/aliases"

## 3rd party integration aliases
timelogger integrations start
integrations_ts=$(timelogger integrations end | tr -dc '0-9')
if [ $integrations_ts -ge 500 ]; then; echo "Runtime of sourcing general integrations was $integrations_ts ms. A bit too high :{"; fi

## ------------- Don't put anything (else) under this line ------------
alert_unused_logs
timelogger zsh end
## ------------------------- THE END OF ZSHRC -------------------------

# () {
#   local z=$'\0'
#   PROMPT='${${${$(spaceship_prompt)//\%\%/'$z'}//\%B}//'$z'/%%}'
# }
