#!/usr/bin/env zsh

SCRIPT_DIR=$(dirname ${(%):-%x})

source "$HOME/config/zshrc/log"
timelogger zsh start

ZSH_THEME="spaceship"; SPACESHIP_BATTERY_SHOW='never'
# https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# https://github.com/denysdovhan/spaceship-zsh-theme
# https://github.com/mbadolato/iTerm2-Color-Schemes#installation-instructions

alias zshrc="code $HOME/config/zshrc"
alias .config="code ~/config"

# IMPORTANT: oh-my-zsh must be installed for making next section work.
# What add-ons do you want to use? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    fzf                     # https://github.com/junegunn/fzf#using-homebrew-or-linuxbrew
    zsh-autosuggestions     # https://github.com/zsh-users/zsh-autosuggestions#oh-my-zsh
    zsh-syntax-highlighting # https://github.com/zsh-users/zsh-syntax-highlighting

    git
    git-extras
    gnu-utils

    golang
    # docker
    # docker-compose
    # kubectl
)

[ ! -d $HOME/.oh-my-zsh ] && echo "oh-my-zsh is not installed" || source "$HOME/.oh-my-zsh/oh-my-zsh.sh"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
# To reload .zshrc: 'source .zshrc' or just type 'zsh'
source "$HOME/.config/zshrc/routes"

## 3rd party integration aliases
timelogger integrations start
integrations_ts=$(timelogger integrations end | tr -dc '0-9')
if [ $integrations_ts -ge 500 ]; then; echo "Runtime of sourcing general integrations was $integrations_ts ms. A bit too high :{"; fi

## ------------- Don't put anything (else) under this line ------------
alert_unused_logs
timelogger zsh end
## ------------------------- THE END OF ZSHRC -------------------------
