#!/bin/bash

## Useful aliases
for f in "$ZSH_CUSTOM_CONFIG_ALIASES"/utils/*; do source "$f"; done

## Operating System aliases
CURRENT_OS="$(uname -a | awk '{print $1}')"
if [ -z "$CURRENT_OS" ]; then
    echo "\$CURRENT_OS couldn't be found"
else
    if [ "$CURRENT_OS" = "Darwin" ]; then
        source "$ZSH_CUSTOM_CONFIG_ALIASES/os/macos/aliases"
    fi
fi

## Personal aliases
for f in "$ZSH_CUSTOM_CONFIG_ALIASES"/nruault/*; do source "$f"; done

# If secrets aliases don't exist, create an empty file
if ! [ -d $ZSH_CUSTOM_CONFIG_ALIASES/secrets ]; then
    mkdir -p $ZSH_CUSTOM_CONFIG_ALIASES/secrets
    touch $ZSH_CUSTOM_CONFIG_ALIASES/secrets/secrets
fi

# Load secrets aliases
SECRETS_FILES=($(ls "$ZSH_CUSTOM_CONFIG_ALIASES/secrets" | grep -v '\.')) # Trick to disregard the non-aliases files
for file in $SECRETS_FILES; do
    source "$ZSH_CUSTOM_CONFIG_ALIASES/secrets/$file"
done
