#!/bin/bash

DOCKER_SCRIPTS_PATH="docker/scripts"

alias dk="$HOME/<PATH>/run.sh $@"
alias dkclean="sh $ZSH_CUSTOM_CONFIG_ALIASES/$DOCKER_SCRIPTS_PATH/docker_clean_all.sh"
alias dkcreate="sh $ZSH_CUSTOM_CONFIG_ALIASES/$DOCKER_SCRIPTS_PATH/docker_turn_on.sh"
alias dklightclean="sh $ZSH_CUSTOM_CONFIG_ALIASES/$DOCKER_SCRIPTS_PATH/docker_light_clean.sh"
alias dkprune='docker system prune --volumes'
alias dkstatus="docker ps -q | xargs  docker stats --no-stream"
alias unsetkube='kubectl config unset current-context'
alias dkstop='docker stop $(docker ps -aq)'
# dkrm='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)' && docker volume prune

# how-to-remove-docker-images-containers-and-volumes
# https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes

function dklist(){
    echo '\n*** images ***' && docker images -a
    echo '\n*** volumes ***' && docker volume ls
    echo '\n*** containers ***' && docker ps -a
}

alias dkps='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Ports}}\t{{.Names}}"'

# You can put this into ~/.docker/config.json to make it the default format.
alias dki='echo "\n___DOCKER IMAGES____ " && docker images -a && echo "\n___DOCKER COMPOSE IMAGES____ " && docker-compose images'

####
# DOCKER PERMISSION ISSUES?
# - docker-compose run --rm --service-ports -u root devenv-node-cp
# - docker run -u root devenv-node-cp

####
# DOCKER DOCS
#
# https://stackoverflow.com/a/20352563/4349318
# Start a simple SMTP server with Python like so:
# 	$ python -m smtpd -n -c DebuggingServer localhost:1025
# 		TIP: Enter to the container through bash
# 		(docker exec -it -u root <container_name> bash) and run the python command
