#!/bin/bash

### Fix slowness of pastes with zsh-syntax-highlighting.zsh
# https://github.com/vercel/hyper/issues/1276
# https://github.com/zsh-users/zsh-syntax-highlighting/issues/295
# https://github.com/magicdude4eva/iterm-oh-my-zsh-powerlevel10k
# zstyle ':bracketed-paste-magic' active-widgets '.self-*'
