#!/bin/bash

### GIT
# https://github.com/ohmyzsh/ohmyzsh/wiki/Cheatsheet#git
alias gamod="git ls-files --modified | xargs git add"

# Remove all your LOCAL git branches but keep master and the current branch:
alias gbreset='git branch --merged | grep -v \* | xargs git branch -D '
# - git branch | egrep -v "(master|dev|\*)" | xargs git branch -D
# - git branch | grep -v "master\|dev" | xargs git branch -D

alias githooksconfig='git config --global core.hooksPath ~/.config/git/hooks/'
# USEFUL COMMANDS:
#   - git diff origin/master --name-only -- '*.go' ':(exclude)vendor/*'
#   - git config --global alias.dirdiff 'diff -p --stat -w --no-index'
alias gl='git log --graph --decorate --pretty=oneline --abbrev-commit'

grbs_usage="pro_rebase [<number] -- Sources any integration given a list

How grbs works:
  Put as first param the number of commits you want to cover (1-N).
  e.g: 'pro_rebase 3' == (git rebase -i HEAD~3)
  Squash commits or whatever and then push your chages with --force
"
function grbs() {
    # https://stackoverflow.com/a/927386
    regex='^[0-9]+$'
    if [[ $@ =~ $regex ]]; then
        git rebase -i HEAD~"$@"
        echo "Remember to push with --force flag."
    else
        pro_rebase_usage
    fi
}

gpo() { git push origin $(git branch --show-current) }
gpos() { git push origin $(git branch --show-current) -o ci.skip } # Gitlab
