#!/bin/bash

alias hs='history | grep' # commands history for non-interactive terminals or terminals without fzf
alias hibernate="sudo systemctl hibernate"
alias \?='type -a $*'

# Networks
alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'
alias localhosts='ifconfig | grep "inet " | grep -v 127.0.0.1' # https://stackoverflow.com/a/4779992

# CP command, do rsync if file is a folder or higher than 50MB  // rsync -ah --progress
alias cp='rsync -ah --progress'
alias rm="rm -i"

function search() { find / -name "$@" | echo; }

alias pgstart='pg_ctl -D /usr/local/var/postgres start'
alias pgstop='pg_ctl -D /usr/local/var/postgres stop'
