#!/bin/bash

# alias killport='netstat -vanp tcp | grep'
alias notebook='/anaconda3/bin/jupyter_mac.command ; exit;'

# dot_clean -> Remove dot-underscore files. Merges ._* files with corresponding native files. # https://ss64.com/osx/dot_clean.html
alias ds_clean="find . -name '.DS_Store' -type f -delete"

function whoamipro() {
    echo '*** $whoami ***' && whoami
    echo '*** $groups $(whoami) ***' && groups $(whoami) | cut -d' ' -f1
    echo '*** $id ***' && id
}

function myip() {
    echo ">> public ip / curl <remote_url>"
    curl http://ipecho.net/plain
    echo

    echo ">> private ip / ipconfig"
    ## MACOS
    ipconfig getifaddr en0 # ifconfig | grep "inet "

    echo ">> default gateway (usually router) / netstat"
    netstat -nr | grep -E "default.*en0" --color=never
}

SPIDER="""
    _
 _\( )/_  Searching and killing
  /(O)\   service...
"""
NO_PARAM_ERROR="""
[INFO]: You need to run this function with at least one string parameter.
"""

function killapp() {
    if [[ -z "$1" ]]; then
        echo $NO_PARAM_ERROR
        return
    else
        pids=$(ps aux | grep -Ei "$@" | awk '{print $2}')

        if [[ -z "$pids" ]]; then
            echo "Couldn't be found any PID related to the given application."
            return
        else
            echo $SPIDER
            echo "Related PIDS found:\n$pids"
            kill -9 $(ps aux | grep -Ei "$@" | awk '{print $2}')
            return
        fi
    fi
}

function killport() {
    if [[ -z "$1" ]]; then
        echo $NO_PARAM_ERROR
        return
    else
        pids=$(netstat -vanp tcp | grep "$@" | awk '{print $9}')

        if [[ -z "$pids" ]]; then
            echo "Couldn't be found any PID related to the given port."
            return
        else
            echo $SPIDER
            echo "Related PIDS found:\n$pids"
            kill -9 $(netstat -vanp tcp | grep "$@" | awk '{print $9}')
            return
        fi
    fi
}

function findapp() {
    if [[ -z "$1" ]]; then
        echo $NO_PARAM_ERROR
        return
    else
        apps=$(ps axc | grep --ignore-case "$@")

        if [[ -z "$apps" ]]; then
            echo "Couldn't be found any PID related to the given app name."
            return
        else
            echo "Related apps found:\n$apps"
            return
        fi
    fi
}

function getUDID() {
    # xctrace list lists capabilities of the current running environment, such as devices or templates
    xcrun xctrace list devices

    # system_profiler reports system hardware and software configuration
    # system_profiler SPUSBDataType | sed -n -e '/iPad/,/Serial/p' -e '/iPhone/,/Serial/p' | grep "Serial Number:" | awk -F ": " '{print $2}'
}

function memusg() {
    echo "Which type of mem usage reporter do you want to use? < time / script >:"
    read memusg_source

    case $memusg_source in
    time)
        echo "alias for /usr/bin/time -l $@"
        /usr/bin/time -l $@
        echo "\n Maximum resident set size reports the peak RAM usage."
        ;;
    script)
        sh $ZSH_CUSTOM_CONFIG_ALIASES/nruault/assets/memusg.sh $@
        ;;
    esac
}

# $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/highlighters/brackets/brackets-highlighter.zsh

### How to use Terminal to send keystrokes?
## osascript -e 'tell application "System Events" to keystroke "q" using {control down, command down}'
