#!/bin/bash

PATH=$(getconf PATH)
PATH="$PATH:/usr/local/bin"
PATH="$PATH:/usr/local/sbin"
PATH="$PATH:$HOME/bin"
PATH="$PATH:/usr/local/opt/fzf/bin"  # fuzzy finder: https://github.com/junegunn/fzf
PATH="$PATH:/usr/local/opt/grep/libexec/gnubin"  # Using another grep function
# PATH="$PATH:/opt/X11/bin"  # Quartz: https://www.xquartz.org/Developer-Info.html

### SET PROFILE ###
source /etc/profile # System-wide .profile for sh(1)

NPM_CONFIG_PREFIX=~/.npm-global

### Golang (config) Paths ###
# https://golang.org/doc/code.html#GOPATH
export GOPATH=$(go env GOPATH) # (gopaths are in 'go env')
export PATH=$PATH:$GOPATH/bin
alias go='/usr/local/go/bin/go'
# export GOROOT=$HOME/go
# export PATH=$PATH:$GOROOT/bin
# Setting up git for golang
# https://stackoverflow.com/questions/32232655/go-get-results-in-terminal-prompts-disabled-error-for-github-private-repo

### ZSH advice (?)###
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"

export PATH

# TODO: Code here an IF to check if fzf exists and prints and error if not.
export FZF_BASE=/usr/local/bin/fzf  # https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/fzf
# export GOPATH=$(/usr/local/go/bin/go env GOPATH)
# MANPATH="/usr/local/opt/grep/libexec/gnuman:$MANPATH"; export MANPATH
