#!/bin/bash

USE_GKE_GCLOUD_AUTH_PLUGIN=True

alias kdev="kubectl config use-context $KUBE_CONTEXT_DEV"
alias kprod="kubectl config use-context $KUBE_CONTEXT_PROD"
alias kctx="kubectl config get-contexts"

alias kport="kubectl port-forward $1 $2"
alias kl="kubectl logs -n $1 $2 --all-containers -f"
