# start=$(($(date +'%s * 1000 + %-N / 1000000')))
start=$(python3 -c 'from time import time; print(int(round(time() * 1000)))')
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"  # (default)
ZSH_THEME="spaceship"  # https://github.com/denysdovhan/spaceship-zsh-theme
SPACESHIP_BATTERY_ALWAYS_SHOW=false


# Which would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    fzf-zsh  # https://github.com/junegunn/fzf
    docker
    zsh-autosuggestions  # https://github.com/zsh-users/zsh-autosuggestions#oh-my-zsh
    zsh-syntax-highlighting  # https://github.com/zsh-users/zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $HOME/.zshrc-config/default_aliases


# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
# To reload .zshrc: 'source .zshrc' or just type 'zsh'

## Useful alias
source $HOME/.zshrc-config/fix_zsh
## Useful alias
source $HOME/.zshrc-config/useful_aliases
## Qvantel useful alias
source $HOME/.zshrc-config/qvantel_aliases
### Docker useful alias
source $HOME/.zshrc-config/docker_aliases
## Useful macos alias
source $HOME/.zshrc-config/macosx_aliases

# export PATH="/usr/local/opt/sphinx-doc/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# end=$(($(date +'%s * 1000 + %-N / 1000000'))); runtime=$((end-start)); echo "Runtime of zshrc was $runtime ms."
end=$(python -c 'from time import time; print(int(round(time() * 1000)))'); runtime=$((end-start)); echo "Runtime of zshrc was $runtime ms."
