#!/bin/bash

# To remove duplicate items in fzf prompt,
# add the following lines into ~/.zshrc:

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000

setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
# setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
# setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt PUSHD_IGNORE_DUPS

setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

export FZF_DEFAULT_OPTS='-e'

# References:
# Prevent the iTerm2 hotkey window from losing focus: https://superuser.com/questions/1100918/how-can-i-prevent-the-iterm2-hotkey-window-from-losing-focus
# Avoid duplicate entries: https://github.com/junegunn/fzf/issues/600
function rm-zshdup() {
    cp ~/.zsh_history{,-old}
    tmpFile=`mktemp`
    awk -F ";" '!seen[$2]++' ~/.zsh_history > $tmpFile
    mv $tmpFile ~/.zsh_history
}

# Fix a locale setting warning from Perl
#     perl: warning: Setting locale failed.
#     perl: warning: Please check that your locale settings:
#         LANGUAGE = (unset),
#         LC_ALL = (unset),
#         LC_CTYPE = "UTF-8",
#         LC_TERMINAL = "iTerm2",
#         LC_TERMINAL_VERSION = "3.4.8",
#         LANG = "C.UTF-8"
#         are supported and installed on your system.
#     perl: warning: Falling back to a fallback locale ("C.UTF-8").
# LC_ALL="en_EN.UTF-8"
# LANGUAGE="en_EN.UTF-8"

# Disabling suggestion for large buffers

ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
